apiVersion: v1
kind: Pod
metadata:
  name: cats
  labels:
    app: cats
spec:
  containers:
   - name: cats
     image: 054326382769.dkr.ecr.us-east-1.amazonaws.com/assignment2:cat
     ports: 
     - containerPort: 80
     