apiVersion: v1
kind: Pod
metadata:
  name: dogs
  labels:
    app: dogs
spec:
  containers:
   - name: dogs
     image: 054326382769.dkr.ecr.us-east-1.amazonaws.com/assignment2:dog
     ports: 
     - containerPort: 80
     