apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicas
  labels:
    app: dogs
spec:
  replicas: 3             
  selector:               
    matchLabels:
      app: dogs
  template:           
    metadata:
      labels:
        app: dogs    
    spec:
      containers:         
      - name: dogs
        image: 054326382769.dkr.ecr.us-east-1.amazonaws.com/assignment2:dog
        ports:
       